[package]
name = "stm32f103xx-usb"
version = "0.1.0"
authors = ["Matti Virkkunen <mvirkkunen@gmail.com>"]

[dependencies]
bare-metal = "0.2.3"
cortex-m = "0.5.4"
stm32f103xx = { version = "0.10.0", features = ["rt"] }
stm32f103xx-hal = { git = "https://github.com/japaric/stm32f103xx-hal", rev = "d1bfbbf9148fc3b9d095fdb3f299aca4070531d8" }
vcell = "0.1.0"
usb-device = { git = "https://github.com/mvirkkunen/usb-device", rev = "2e07f982068f7d3594b51fe9e30f43f271638174" }

[dev-dependencies]
cortex-m-rt = "0.5.2"
panic-semihosting = "0.5.1"
