[package]
name = "stm32f429-usbd-fs"
version = "0.1.0"
authors = ["Vadim Kaushan <admin@disasm.info>"]
edition = "2018"

[dependencies]
cortex-m = { version = "0.6.0", optional = true }
vcell = "0.1.0"
usb-device = "0.2.2"

[dependencies.stm32ral]
git = "https://github.com/Disasm/stm32ral"
rev = "aa95c633b7bf535c96d7eac997deb361aabae87c"
features = ["stm32f429"]

[features]
hs = []
fs = []
stm32f429xx = ['cortex-m']
stm32f401xx = ['cortex-m', 'fs']
