[package]
name = "stm32f103xx-usb"
version = "0.1.0"
edition = "2018"
authors = ["Matti Virkkunen <mvirkkunen@gmail.com>"]

[dependencies]
bare-metal = "0.2.4"
cortex-m = "0.5.8"
stm32f103xx = { version = "0.11.0", features = ["rt"] }
stm32f103xx-hal = { git = "https://github.com/japaric/stm32f103xx-hal", rev = "cabc005ac2c678f1e6a0c57ababfc1d0581f0ad6" }
vcell = "0.1.0"
usb-device = { git = "https://github.com/mvirkkunen/usb-device", rev = "e5b87a9cd18e8223be3463096fda62daee90e2d3" }

[dev-dependencies]
cortex-m-rt = "0.6.7"
panic-semihosting = "0.5.1"
